
REVOKE ALL ON FUNCTION public._lovable_exec_sql(text) FROM PUBLIC, anon, authenticated, service_role;
DROP FUNCTION IF EXISTS public._lovable_exec_sql(text);

INSERT INTO public.permissions (code, label, description) VALUES
  ('can_create_form','Buat form','Buat form'),
  ('can_edit_form','Edit form','Edit form'),
  ('can_publish_form','Publikasikan form','Publikasikan form'),
  ('can_assign_form','Assign form','Assign form ke target'),
  ('can_verify_submission','Verifikasi submission','Verifikasi submission'),
  ('can_approve_submission','Setujui submission','Setujui submission'),
  ('can_reject_submission','Tolak submission','Tolak submission'),
  ('can_request_revision','Minta revisi','Minta revisi submission'),
  ('can_view_sensitive_document','Lihat dokumen sensitif','Lihat dokumen sensitif'),
  ('can_download_document','Unduh dokumen','Unduh dokumen'),
  ('can_share_document','Bagikan dokumen','Bagikan dokumen'),
  ('can_request_document','Minta dokumen','Minta dokumen'),
  ('can_manage_users','Kelola user','Kelola user'),
  ('can_manage_opd','Kelola OPD','Kelola OPD'),
  ('can_view_audit_logs','Lihat audit log','Lihat audit log'),
  ('can_export_data','Ekspor data','Ekspor data'),
  ('can_manage_roles','Kelola role','Kelola role'),
  ('can_manage_forms','Kelola form','Kelola form'),
  ('can_request_data','Minta data','Minta data'),
  ('can_approve_data_request','Setujui permintaan data','Setujui permintaan data'),
  ('can_approve_registration','Setujui pendaftaran','Setujui pendaftaran'),
  ('view_all_opd','Lihat semua OPD','Lihat semua OPD'),
  ('view_all_submissions','Lihat semua submission','Lihat semua submission'),
  ('view_all_attendance','Lihat semua absensi','Lihat semua absensi'),
  ('view_all_assets','Lihat semua aset','Lihat semua aset'),
  ('view_all_datasets','Lihat semua dataset','Lihat semua dataset'),
  ('view_all_reports','Lihat semua laporan','Lihat semua laporan'),
  ('view_all_performance','Lihat semua kinerja','Lihat semua kinerja'),
  ('view_all_surveys','Lihat semua survei','Lihat semua survei'),
  ('view_kabupaten_dashboard','Dashboard Kabupaten','Lihat dashboard kabupaten'),
  ('view_executive_dashboard','Dashboard Eksekutif','Lihat dashboard eksekutif'),
  ('view_cross_opd_analytics','Analitik Lintas OPD','Lihat analitik lintas OPD'),
  ('pemda.view','Lihat Pemda','Akses tampilan Pemda'),
  ('pemda.manage','Kelola Pemda','Kelola data Pemda'),
  ('pemda.monitor','Monitor Pemda','Monitor Pemda'),
  ('executive.view','Lihat Eksekutif','Akses tampilan eksekutif'),
  ('executive.approve','Persetujuan Eksekutif','Persetujuan eksekutif (Bupati)'),
  ('executive.sign','Tanda Tangan Eksekutif','Tanda tangan eksekutif (Bupati)'),
  ('executive.disposition','Disposisi Eksekutif','Disposisi eksekutif (Bupati)')
ON CONFLICT (code) DO NOTHING;
